apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nginx-app-certificate
spec:
  dnsNames:
    - nginx-app.mydomain.com
  secretName: nginx-app-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
