---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registry-vol
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi